# Generated by Django 4.1.3 on 2023-01-09 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_post_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='img',
            field=models.ImageField(default='blog/static/img/default.png', max_length=200, upload_to='blog/static/img'),
        ),
    ]
