# Generated by Django 4.1.3 on 2023-01-23 16:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0005_post_views_number_alter_post_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='views_number',
        ),
        migrations.AddField(
            model_name='post',
            name='views_number',
            field=models.ManyToManyField(related_name='views_rating', to=settings.AUTH_USER_MODEL),
        ),
    ]
