# Generated by Django 4.1.3 on 2023-01-31 17:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0006_remove_post_views_number_post_views_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='views_number',
            field=models.ManyToManyField(blank=True, related_name='views_rating', to=settings.AUTH_USER_MODEL),
        ),
    ]
