# Generated by Django 4.1.4 on 2023-02-19 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('info', models.TextField(blank=True)),
                ('category_slug', models.CharField(default='category_main', max_length=80)),
                ('img', models.ImageField(default='default.jpg', upload_to='blog/static/img/categories', verbose_name='Зображення категорії')),
            ],
            options={
                'verbose_name_plural': 'Категорії',
            },
        ),
    ]
